travis: fix missing constructor error for both gcc 7,8
Error seems to unrecognize the ``[[maybe_unused]]` token with the `if
constexpr`:

error: expected unqualified-id before ‘[’ token

     debug_logger([[maybe_unused]] const std::string_view name) noexcept

lib/src/itm-common.hpp:1796:18: error: expected ‘)’ before ‘[’ token

     debug_logger([[maybe_unused]] const std::string_view name) noexcept

                 ~^